compile:
		ec types.m hash.m server.m peer.m nopester.m
compile_planetlab:
		ec32 types.m hash.m server.m peer.m nopester.m
run:
		emx -R$(host) types.x hash.x server.x peer.x nopester.x
run_planetlab:
		emx32 -R$(host) types.x hash.x server.x peer.x nopester.x
clean:
		rm *.x
